### PR TITLE
 Work on man pages to add alias file documentation.

### PR DESCRIPTION
**Pull request by frederickjh**
Work to fix the man page part of #79 .

### CODE REVIEW

**Comment by frederickjh** [comment]
Will the new `man` page for the `owfs` alias file be added to the wiki via a script or is there something that needs to be done to get it added?

**Comment by frederickjh** [comment]
This is my first time to work on a man page, so there maybe some things that need fixed.

**Comment by ianka** [comment]
I have made a script for that a while ago.

**Comment by ianka** [comment]
I updated the wiki. It's not pretty. Neither my man2md tool nor pandoc are able to create visually appealing markdown from our manpages. Bummer!

**Comment by frederickjh** [comment]
> I have made a script for that a while ago. Let me check.

Hi @ianka Thanks for working on that. I just went to the [owfs.aliasfile man page on the Wiki](https://github.com/owfs/owfs-doc/wiki/owfs.aliasfile) and it looks like some of the formatting is not converting correctly for the wiki. 

image

Here some of the text is  large, that should be small, bold and underline markdown formatting characters can be seen. Strange as I copied this section from `owfs.man`.
image

<hr>

image

The bullets do not get converted. These are formated with **`\(bu`** in the man file.
image

**Comment by frederickjh** [comment]
> I updated the wiki. It's not pretty. Neither my man2md tool nor pandoc are able to create visually appealing markdown from our manpages. Bummer!

@ianka I think some of it is my formatting in the man page. It is my first time I believe I did not do the indentation correctly. Should I just add new commits to this pull request for you to merge?

The other question that comes to mind is; "Should this project consider how they do documentation?"   I think it might be easier to get people involved in writing documentation if they could write it in markdown.

There seem to be a number of Markdown to man page conversion tools but other than your tool I could not find any one step tools. The best I could do was  the following incantation:
```bash
groff -mandoc -Thtml -P -l man5/owfs.aliasfile.man | pandoc -o /tmp/aaa-tmp/test.md -f html -t markdown
```
This prevent  the automatically created table of contents from being generated. Other than the indentation issues, the top title showing styling code, seems to be  the only other formatting issue that I can find. 

In any case I am going to work on the indentation formatting, please let me know how best to submit my new changes to this file.

**Pull request merged**
