### PR TITLE
Add possibility to compile owfs against php7, requires swig > 3.0.11

### PR DESCRIPTION
**Pull request by heinervdm**
Signed-off-by: Thomas Zimmermann <bugs@vdm-design.de>

### CODE REVIEW

**Comment by stromnet** [comment]
Thanks, don't have any php7 setup to test with so I'm just assuming this works!

**Comment by stromnet** [comment]
Sorry, the build broke after merging, see https://travis-ci.org/owfs/owfs/builds/369712444

I have now reverted that commit manually, but GitHub does not reflect it.
Please create a new PR based on current master, and you will hopefully get a Travis build indication directly in the PR :)

**Comment by miccoli** [comment]
Please see <https://www.gnu.org/software/automake/manual/html_node/Usage-of-Conditionals.html>:

the bug is in <https://github.com/owfs/owfs/blob/a9a79b330e334ba80c305905b51e8886b40772d9/configure.ac#L659-L664>
where the `AM_CONDITIONAL([PHP7], ...)` is evaluated conditionally. 

The `AM_CONDITIONAL` should be outside any `if ... fi` block.

**Comment by miccoli** [comment]
I'm having a look at this problem, please see <https://github.com/miccoli/owfs/tree/feature/php7>
when that branch is clean enough I will PR here.

**Comment by heinervdm** [comment]
Thanks for having a look at this, I'm a bit busy at the moment so I can't look at it. I can only tell that somehow it compiles on openSUSE Tumbleweed with this patch. Perhaps autotools there is a bit more error tolerant :-)

**Pull request merged**
